[package]
name = "FtpServer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
base64 = "0.22.1"
serde_bytes = "0.11"
sha256 = "1.0.3"
